baseURL: /
languageCode: en-us
paginate: 6
theme: portio-hugo-data-science
title: Zach's Data Science Portfolio
menu:
  main:
    - name: Home
      url: '#home'
      weight: 1
    - name: About
      url: '#about'
      weight: 2
    - name: Portfolio
      url: '#portfolio'
      weight: 4
    - name: Resume
      url: '#resume'
      weight: 5
    - name: Blog
      url: blog
      weight: 6
  sitemap:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: blog
      weight: 2
params:
  blogPageURL: blog
  contactButtonLabel: Contact Zach
  contactLink: '#contact'
  copyright: All right reserved copyright © Zach Eisenstein 2022
  footerLogo: images/site-navigation/logo2.png
  formspreeURL: YOUR FORMSPREE URL
  googleAnalytics: YOUR GOOGLE ANALYTICS CODE
  logo: images/site-navigation/logo2.png
  social:
    - icon: fa-linkedin-square
      url: https://www.linkedin.com/in/zacharyeisenstein/
      weight: 1
    - icon: fa-twitter-square
      url: https://twitter.com/zscore123
      weight: 2
    - icon: fa-github
      url: https://github.com/zscore314
      weight: 3
